name: Java CI
on:
  push:
    branches:
      - '[1-9]+.[0-9]+.x'
      - master
  pull_request:
    branches:
      - '[1-9]+.[0-9]+.x'
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['17']
    env:
      WORKSPACE: ${{ github.workspace }}
      GRADLE_OPTS: -Xmx1500m -Dfile.encoding=UTF-8
      develocity-access-key: ${{ secrets.GRAILS_DEVELOCITY_ACCESS_KEY  }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Run Assemble
        if: success() && github.event_name == 'push' && matrix.java == '17'
        run: ./gradlew assemble
      - name: Publish to repo.grails.org
        if: success() && github.event_name == 'push' && matrix.java == '17'
        env:
          MAVEN_PUBLISH_URL: ${{ secrets.GRAILS_NEXUS_PUBLISH_SNAPSHOT_URL }}
          MAVEN_PUBLISH_USERNAME: ${{ secrets.NEXUS_USER }}
          MAVEN_PUBLISH_PASSWORD: ${{ secrets.NEXUS_PW  }}
        run: |
          ./gradlew publish
