name: Java CI
on:
  push:
    branches:
      - '[1-9]+.[0-9]+.x'
      - master
  pull_request:
    branches:
      - '[1-9]+.[0-9]+.x'
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['17']
    env:
      WORKSPACE: ${{ github.workspace }}
      GRADLE_OPTS: -Xmx1500m -Dfile.encoding=UTF-8
    steps:
      - name: "📥 Checkout repository"
        uses: actions/checkout@v4
      - name: "☕️ Setup JDK"
        uses: actions/setup-java@v4
        with:
          distribution: liberica
          java-version: ${{ matrix.java }}
      - name: "🐘 Setup Gradle"
        uses: gradle/actions/setup-gradle@v4
        with:
          develocity-access-key: ${{ secrets.GRAILS_DEVELOCITY_ACCESS_KEY  }}
      - name: "🔨 Run Assemble"
        if: github.event_name == 'push' && matrix.java == '17'
        run: ./gradlew assemble
      - name: "📤 Publish Snapshot Artifacts to Apache Snapshot Repo"
        if: github.event_name == 'push' && matrix.java == '17'
        env:
          MAVEN_PUBLISH_URL: ${{ secrets.GRAILS_NEXUS_PUBLISH_SNAPSHOT_URL }}
          MAVEN_PUBLISH_USERNAME: ${{ secrets.NEXUS_USER }}
          MAVEN_PUBLISH_PASSWORD: ${{ secrets.NEXUS_PW  }}
        run: |
          ./gradlew publish
